export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED'

export const GET_STICKY_ARTICLES_REQUEST = 'GET_STICKY_ARTICLES_REQUEST'
export const GET_STICKY_ARTICLES_SUCCESS = 'GET_STICKY_ARTICLES_SUCCESS'
export const GET_STICKY_ARTICLES_FAILED = 'GET_STICKY_ARTICLES_FAILED'

export const CHANGE_TABBAR = 'CHANGE_TABBAR'