export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED'

export const GET_JOKES_REQUEST = 'GET_JOKES_REQUEST'
export const GET_JOKES_SUCCESS = 'GET_JOKES_SUCCESS'
export const GET_JOKES_FAILED = 'GET_JOKES_FAILED'

export const GET_PICTURES_REQUEST = 'GET_PICTURES_REQUEST'
export const GET_PICTURES_SUCCESS = 'GET_PICTURES_SUCCESS'
export const GET_PICTURES_FAILED = 'GET_PICTURES_FAILED'

export const GET_DETAIL_REQUEST = 'GET_DETAIL_REQUEST'
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS'
export const GET_DETAIL_FAILED = 'GET_DETAIL_FAILED'

export const GET_STICKY_ARTICLES_REQUEST = 'GET_STICKY_ARTICLES_REQUEST'
export const GET_STICKY_ARTICLES_SUCCESS = 'GET_STICKY_ARTICLES_SUCCESS'
export const GET_STICKY_ARTICLES_FAILED = 'GET_STICKY_ARTICLES_FAILED'

export const CHANGE_TABBAR = 'CHANGE_TABBAR'