export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED'

export const GET_STICKYPOSTS_REQUEST = 'GET_STICKYPOSTS_REQUEST'
export const GET_STICKYPOSTS_SUCCESS = 'GET_STICKYPOSTS_SUCCESS'
export const GET_STICKYPOSTS_FAILED = 'GET_STICKYPOSTS_FAILED'

export const CHANGE_TABBAR = 'CHANGE_TABBAR'